project:
  name: "SOIPack Demo Avionics - Level A"
  version: "1.0.0"
level: "A"
objectives:
  file: "../../data/objectives/do178c_objectives.min.json"
inputs:
  jira: "requirements.csv"
  reqif: "spec.reqif"
  junit: "results.xml"
  lcov: "lcov.info"
  cobertura: "coverage.xml"
  git: "../.."
output:
  work: ".soipack/level-a/work"
  analysis: ".soipack/level-a/out"
  reports: "dist/level-a/reports"
  release: "release/level-a"
artifacts:
  map: "artifact_map.json"
  directory: "artifacts"
pack:
  name: "soi-pack-demo-level-a.zip"
  input: "dist/level-a"
