project:
  name: "SOIPack Demo Avionics - Level B"
  version: "1.0.0"
level: "B"
objectives:
  file: "../../data/objectives/do178c_objectives.min.json"
inputs:
  jira: "requirements.csv"
  reqif: "spec.reqif"
  junit: "results.xml"
  lcov: "lcov.info"
  cobertura: "coverage.xml"
  git: "../.."
  polyspace: "polyspace/report.json"
  ldra: "ldra/tbvision.json"
  vectorcast: "vectorcast/coverage.json"
output:
  work: ".soipack/level-b/work"
  analysis: ".soipack/level-b/out"
  reports: "dist/level-b/reports"
  release: "release/level-b"
artifacts:
  map: "artifact_map.json"
  directory: "artifacts"
pack:
  name: "soi-pack-demo-level-b.zip"
  input: "dist/level-b"
