export type Locale = 'tr';

const translations: Record<string, string> = {
  'dashboard.title': 'Uyumluluk & İzlenebilirlik Panosu',
  'dashboard.description': 'İş kuyruğu metriklerini ve bekleyen incelemeleri canlı olarak takip edin.',
  'dashboard.credentialsRequired': 'REST kimlik bilgileri gereklidir.',
  'dashboard.queueMetrics': 'Kuyruk Durumu',
  'dashboard.queueError': 'Kuyruk metrikleri alınamadı.',
  'dashboard.queueErrorTitle': 'Kuyruk yüklenemedi',
  'dashboard.queueTotal': 'Toplam İşler',
  'dashboard.queueQueued': 'Bekleyen',
  'dashboard.queueRunning': 'Çalışan',
  'dashboard.queueCompleted': 'Tamamlanan',
  'dashboard.complianceReadiness': 'Uyumluluk Hazırlığı',
  'dashboard.complianceError': 'Uyumluluk özeti alınamadı.',
  'dashboard.complianceErrorTitle': 'Uyumluluk özeti yüklenemedi',
  'dashboard.complianceEmpty': 'Uyumluluk özeti bulunamadı',
  'dashboard.complianceStatusReady': 'Hazır',
  'dashboard.complianceStatusAttention': 'Eylem Gerekli',
  'dashboard.complianceLastComputed': 'Son hesaplama:',
  'dashboard.complianceOpenObjectivesLabel': 'Açık hedefler:',
  'dashboard.complianceCoverage': 'Hazırlık (%)',
  'dashboard.complianceCovered': 'Tamamlanan hedef',
  'dashboard.compliancePartial': 'Kısmi hedef',
  'dashboard.complianceMissing': 'Eksik hedef',
  'dashboard.pendingReviews': 'Bekleyen İncelemeler',
  'dashboard.reviewError': 'İnceleme listesi alınamadı.',
  'dashboard.reviewErrorTitle': 'İncelemeler yüklenemedi',
  'dashboard.noPendingReviews': 'Bekleyen inceleme bulunmuyor',
  'dashboard.reviewId': 'İnceleme',
  'dashboard.reviewTarget': 'Hedef',
  'dashboard.reviewApprovers': 'Onaycılar',
  'dashboard.reviewUpdatedAt': 'Güncelleme',
  'dashboard.health': 'Sistem Sağlığı',
  'logs.title': 'Denetim Kayıtları',
  'logs.description': 'Tüm denetim olaylarını görüntüleyin ve dışa aktarın.',
  'logs.exportCsv': 'CSV Dışa Aktar',
  'logs.empty': 'Henüz kayıt bulunmuyor',
  'logs.error': 'Denetim kayıtları alınamadı.',
  'logs.errorTitle': 'Denetim kayıtları yüklenemedi',
  'logs.credentialsRequired': 'REST kimlik bilgileri gereklidir.',
  'logs.filter.tenant': 'Kiracı filtresi',
  'logs.filter.actor': 'Kullanıcı filtresi',
  'logs.table.timestamp': 'Zaman',
  'logs.table.actor': 'Kullanıcı',
  'logs.table.tenant': 'Kiracı',
  'logs.table.action': 'Eylem',
  'logs.table.target': 'Hedef',
  'notifications.success': 'Başarıyla kaydedildi',
  'settings.title': 'Yönetim Ayarları',
  'settings.description': 'Güvenlik, lisans ve güncelleme politikalarını yönetin.',
  'settings.tab.general': 'Genel',
  'settings.tab.security': 'Güvenlik',
  'settings.tab.license': 'Lisans',
  'settings.tab.updates': 'Güncellemeler',
  'settings.environment': 'Çalışma Ortamı',
  'settings.licenseSerial': 'Lisans Seri',
  'settings.licenseExpiry': 'Lisans Bitişi',
  'settings.features': 'Aktif Özellikler',
  'settings.updatePolicy': 'Güncelleme Politikası',
  'audit.banner': 'Denetim kayıtları kaydediliyor ve 90 gün saklanıyor.',
  'wizard.sign.cta': 'Ayarları Kaydet',
  'wizard.deploy.cta': 'Politikayı Güncelle',
  'status.up': 'Çevrimiçi',
  'status.down': 'Kapalı',
  'status.degraded': 'Kısmi Hizmet',
};

export function translate(_locale: Locale, key: string): string {
  return translations[key] ?? key;
}
