export type Locale = 'en' | 'tr';

const enTranslations: Record<string, string> = {
  'app.languageLabel': 'Language',
  'app.heroDescription': 'Provide REST credentials to orchestrate imports, monitor analysis, and download compliance packages.',
  'dashboard.title': 'Compliance & Traceability Dashboard',
  'dashboard.description': 'Track job queue metrics and pending reviews in real time.',
  'dashboard.credentialsRequired': 'REST credentials are required.',
  'dashboard.queueMetrics': 'Queue Status',
  'dashboard.queueError': 'Unable to load queue metrics.',
  'dashboard.queueErrorTitle': 'Queue failed to load',
  'dashboard.queueTotal': 'Total Jobs',
  'dashboard.queueQueued': 'Queued',
  'dashboard.queueRunning': 'Running',
  'dashboard.queueCompleted': 'Completed',
  'dashboard.complianceReadiness': 'Compliance Readiness',
  'dashboard.complianceError': 'Unable to load compliance summary.',
  'dashboard.complianceErrorTitle': 'Compliance summary failed to load',
  'dashboard.complianceEmpty': 'No compliance summary available',
  'dashboard.complianceStatusReady': 'Ready',
  'dashboard.complianceStatusAttention': 'Action Required',
  'dashboard.complianceLastComputed': 'Last computed:',
  'dashboard.complianceOpenObjectivesLabel': 'Open objectives:',
  'dashboard.complianceCoverage': 'Readiness (%)',
  'dashboard.complianceCovered': 'Completed objective',
  'dashboard.compliancePartial': 'Partial objective',
  'dashboard.complianceMissing': 'Missing objective',
  'dashboard.changeImpactTitle': 'Change Impact',
  'dashboard.changeImpactSubtitle': 'Highlighted records compared to the baseline',
  'dashboard.changeImpactEmpty': 'No change impact data available.',
  'dashboard.changeImpactTotalLabel': 'Records',
  'dashboard.changeImpactTopLabel': 'Top critical records',
  'dashboard.changeImpactListLabel': 'Change impact entries',
  'dashboard.changeImpactMoreEntries': 'more record',
  'dashboard.changeImpactNoReason': 'No reason provided.',
  'dashboard.changeImpactMoreReasons': 'more reason',
  'dashboard.changeImpactSeverityCritical': 'Critical',
  'dashboard.changeImpactSeverityHigh': 'High',
  'dashboard.changeImpactSeverityMedium': 'Medium',
  'dashboard.changeImpactSeverityLow': 'Low',
  'dashboard.changeImpactState.added': 'Added',
  'dashboard.changeImpactState.removed': 'Removed',
  'dashboard.changeImpactState.modified': 'Updated',
  'dashboard.changeImpactState.impacted': 'Impacted',
  'dashboard.changeImpactType.requirement': 'Requirement',
  'dashboard.changeImpactType.test': 'Test',
  'dashboard.changeImpactType.code': 'Code',
  'dashboard.changeImpactType.design': 'Design',
  'dashboard.remediationPlanTitle': 'Remediation Plan',
  'dashboard.remediationPlanSubtitle': 'Prioritized actions to close compliance gaps',
  'dashboard.remediationPlanError': 'Unable to load remediation plan.',
  'dashboard.remediationPlanErrorTitle': 'Remediation plan failed to load',
  'dashboard.remediationPlanEmpty': 'No remediation actions required.',
  'dashboard.remediationPlanGeneratedAt': 'Generated:',
  'dashboard.remediationPlanMoreActions': 'more actions prioritized',
  'dashboard.remediationPlanActionsTotal': 'Actions',
  'dashboard.remediationPlanObjectiveLinkLabel': 'View objective',
  'dashboard.remediationPlanArtifactsLabel': 'Missing artifacts',
  'dashboard.remediationPlanLinksLabel': 'Related artifacts',
  'dashboard.remediationPriority.critical': 'Critical',
  'dashboard.remediationPriority.high': 'High',
  'dashboard.remediationPriority.medium': 'Medium',
  'dashboard.remediationPriority.low': 'Low',
  'dashboard.remediationIssue.gap.analysis': 'Analysis evidence needed',
  'dashboard.remediationIssue.gap.tests': 'Test evidence needed',
  'dashboard.remediationIssue.gap.coverage': 'Coverage evidence needed',
  'dashboard.remediationIssue.gap.trace': 'Trace links missing',
  'dashboard.remediationIssue.gap.reviews': 'Review records missing',
  'dashboard.remediationIssue.gap.plans': 'Plans missing',
  'dashboard.remediationIssue.gap.standards': 'Standards mapping missing',
  'dashboard.remediationIssue.gap.configuration': 'Configuration records missing',
  'dashboard.remediationIssue.gap.quality': 'Quality records missing',
  'dashboard.remediationIssue.gap.issues': 'Problem reports missing',
  'dashboard.remediationIssue.gap.conformity': 'Conformity records missing',
  'dashboard.remediationIssue.independence.required': 'Independent verification required',
  'dashboard.remediationIssue.independence.recommended': 'Independent review recommended',
  'dashboard.remediationIssue.independence.none': 'Independence coverage pending',
  'dashboard.remediationArtifact.plan': 'Plan',
  'dashboard.remediationArtifact.standard': 'Standard',
  'dashboard.remediationArtifact.review': 'Review',
  'dashboard.remediationArtifact.analysis': 'Analysis',
  'dashboard.remediationArtifact.test': 'Test',
  'dashboard.remediationArtifact.coverage_stmt': 'Statement coverage',
  'dashboard.remediationArtifact.coverage_dec': 'Decision coverage',
  'dashboard.remediationArtifact.coverage_mcdc': 'MC/DC coverage',
  'dashboard.remediationArtifact.trace': 'Traceability',
  'dashboard.remediationArtifact.cm_record': 'Configuration record',
  'dashboard.remediationArtifact.qa_record': 'Quality record',
  'dashboard.remediationArtifact.problem_report': 'Problem report',
  'dashboard.remediationArtifact.conformity': 'Conformity record',
  'dashboard.remediationArtifact.design': 'Design artifact',
  'dashboard.independenceTitle': 'Independence Checks',
  'dashboard.independenceSubtitle': 'Objectives that require independent validation',
  'dashboard.independenceAllClear': 'All objectives requiring independent validation are complete.',
  'dashboard.independenceUnavailable': 'Independence summary unavailable.',
  'dashboard.independenceOpenSummary': 'Open independence objectives',
  'dashboard.independencePartial': 'Partial',
  'dashboard.independenceMissing': 'Missing',
  'dashboard.independenceLinkLabel': 'View objective',
  'dashboard.pendingReviews': 'Pending Reviews',
  'dashboard.reviewError': 'Unable to load review list.',
  'dashboard.reviewErrorTitle': 'Reviews failed to load',
  'dashboard.noPendingReviews': 'No pending reviews',
  'dashboard.reviewId': 'Review',
  'dashboard.reviewTarget': 'Target',
  'dashboard.reviewApprovers': 'Approvers',
  'dashboard.reviewUpdatedAt': 'Updated',
  'dashboard.changeRequests': 'Jira Change Requests',
  'dashboard.changeRequestsError': 'Unable to load Jira change requests.',
  'dashboard.changeRequestsErrorTitle': 'Change requests failed to load',
  'dashboard.changeRequestsEmpty': 'No pending change requests',
  'dashboard.changeRequestsKey': 'Key',
  'dashboard.changeRequestsSummary': 'Summary',
  'dashboard.changeRequestsStatus': 'Status',
  'dashboard.changeRequestsAssignee': 'Assignee',
  'dashboard.changeRequestsUpdatedAt': 'Updated',
  'dashboard.changeRequestsAttachments': 'Attachments',
  'dashboard.health': 'System Health',
  'logs.title': 'Audit Logs',
  'logs.description': 'View and export all audit events.',
  'logs.exportCsv': 'Export CSV',
  'logs.empty': 'No entries yet',
  'logs.error': 'Unable to load audit logs.',
  'logs.errorTitle': 'Audit logs failed to load',
  'logs.credentialsRequired': 'REST credentials are required.',
  'logs.filter.tenant': 'Tenant filter',
  'logs.filter.actor': 'User filter',
  'logs.table.timestamp': 'Time',
  'logs.table.actor': 'User',
  'logs.table.tenant': 'Tenant',
  'logs.table.action': 'Action',
  'logs.table.target': 'Target',
  'notifications.success': 'Saved successfully',
  'settings.title': 'Administration Settings',
  'settings.description': 'Manage security, licensing, and update policies.',
  'settings.tab.general': 'General',
  'settings.tab.security': 'Security',
  'settings.tab.license': 'License',
  'settings.tab.updates': 'Updates',
  'settings.environment': 'Environment',
  'settings.licenseSerial': 'License Serial',
  'settings.licenseExpiry': 'License Expiry',
  'settings.features': 'Enabled Features',
  'settings.updatePolicy': 'Update Policy',
  'audit.banner': 'Audit logs are captured and retained for 90 days.',
  'wizard.sign.cta': 'Save Settings',
  'wizard.deploy.cta': 'Update Policy',
  'status.up': 'Online',
  'status.down': 'Offline',
  'status.degraded': 'Degraded Service',
  'common.ok': 'OK'
};

const trTranslations: Record<string, string> = {
  'app.languageLabel': 'Dil',
  'app.heroDescription': 'Geçerli bir REST token ile import, analyze ve report işlerinizin durumunu takip edip oluşan uyum ve izlenebilirlik çıktılarının özetini görüntüleyebilir, rapor artefaktlarını indirebilirsiniz.',
  'dashboard.title': 'Uyumluluk & İzlenebilirlik Panosu',
  'dashboard.description': 'İş kuyruğu metriklerini ve bekleyen incelemeleri canlı olarak takip edin.',
  'dashboard.credentialsRequired': 'REST kimlik bilgileri gereklidir.',
  'dashboard.queueMetrics': 'Kuyruk Durumu',
  'dashboard.queueError': 'Kuyruk metrikleri alınamadı.',
  'dashboard.queueErrorTitle': 'Kuyruk yüklenemedi',
  'dashboard.queueTotal': 'Toplam İşler',
  'dashboard.queueQueued': 'Bekleyen',
  'dashboard.queueRunning': 'Çalışan',
  'dashboard.queueCompleted': 'Tamamlanan',
  'dashboard.complianceReadiness': 'Uyumluluk Hazırlığı',
  'dashboard.complianceError': 'Uyumluluk özeti alınamadı.',
  'dashboard.complianceErrorTitle': 'Uyumluluk özeti yüklenemedi',
  'dashboard.complianceEmpty': 'Uyumluluk özeti bulunamadı',
  'dashboard.complianceStatusReady': 'Hazır',
  'dashboard.complianceStatusAttention': 'Eylem Gerekli',
  'dashboard.complianceLastComputed': 'Son hesaplama:',
  'dashboard.complianceOpenObjectivesLabel': 'Açık hedefler:',
  'dashboard.complianceCoverage': 'Hazırlık (%)',
  'dashboard.complianceCovered': 'Tamamlanan hedef',
  'dashboard.compliancePartial': 'Kısmi hedef',
  'dashboard.complianceMissing': 'Eksik hedef',
  'dashboard.changeImpactTitle': 'Değişiklik Etkisi',
  'dashboard.changeImpactSubtitle': 'Baseline karşılaştırmasına göre öne çıkan kayıtlar',
  'dashboard.changeImpactEmpty': 'Değişiklik etkisi verisi bulunamadı.',
  'dashboard.changeImpactTotalLabel': 'Kayıtlar',
  'dashboard.changeImpactTopLabel': 'En kritik kayıtlar',
  'dashboard.changeImpactListLabel': 'Değişiklik etkisi öğeleri',
  'dashboard.changeImpactMoreEntries': 'ek kayıt',
  'dashboard.changeImpactNoReason': 'Gerekçe sağlanmadı.',
  'dashboard.changeImpactMoreReasons': 'ek gerekçe',
  'dashboard.changeImpactSeverityCritical': 'Kritik',
  'dashboard.changeImpactSeverityHigh': 'Yüksek',
  'dashboard.changeImpactSeverityMedium': 'Orta',
  'dashboard.changeImpactSeverityLow': 'Düşük',
  'dashboard.changeImpactState.added': 'Eklendi',
  'dashboard.changeImpactState.removed': 'Kaldırıldı',
  'dashboard.changeImpactState.modified': 'Güncellendi',
  'dashboard.changeImpactState.impacted': 'Etkilendi',
  'dashboard.changeImpactType.requirement': 'Gereksinim',
  'dashboard.changeImpactType.test': 'Test',
  'dashboard.changeImpactType.code': 'Kod',
  'dashboard.changeImpactType.design': 'Tasarım',
  'dashboard.remediationPlanTitle': 'İyileştirme Planı',
  'dashboard.remediationPlanSubtitle': 'Uyumluluk boşluklarını kapatmak için öncelikli aksiyonlar',
  'dashboard.remediationPlanError': 'İyileştirme planı alınamadı.',
  'dashboard.remediationPlanErrorTitle': 'İyileştirme planı yüklenemedi',
  'dashboard.remediationPlanEmpty': 'İyileştirme aksiyonu gerekmiyor.',
  'dashboard.remediationPlanGeneratedAt': 'Oluşturulma:',
  'dashboard.remediationPlanMoreActions': 'ek aksiyon önceliklendirildi',
  'dashboard.remediationPlanActionsTotal': 'Aksiyonlar',
  'dashboard.remediationPlanObjectiveLinkLabel': 'Hedefe git',
  'dashboard.remediationPlanArtifactsLabel': 'Eksik artefaktlar',
  'dashboard.remediationPlanLinksLabel': 'İlgili artefaktlar',
  'dashboard.remediationPriority.critical': 'Kritik',
  'dashboard.remediationPriority.high': 'Yüksek',
  'dashboard.remediationPriority.medium': 'Orta',
  'dashboard.remediationPriority.low': 'Düşük',
  'dashboard.remediationIssue.gap.analysis': 'Analiz kanıtı gerekli',
  'dashboard.remediationIssue.gap.tests': 'Test kanıtı gerekli',
  'dashboard.remediationIssue.gap.coverage': 'Kapsam kanıtı gerekli',
  'dashboard.remediationIssue.gap.trace': 'İzlenebilirlik eksik',
  'dashboard.remediationIssue.gap.reviews': 'Gözden geçirme kayıtları eksik',
  'dashboard.remediationIssue.gap.plans': 'Planlar eksik',
  'dashboard.remediationIssue.gap.standards': 'Standart eşlemesi eksik',
  'dashboard.remediationIssue.gap.configuration': 'Konfigürasyon kayıtları eksik',
  'dashboard.remediationIssue.gap.quality': 'Kalite kayıtları eksik',
  'dashboard.remediationIssue.gap.issues': 'Problem raporları eksik',
  'dashboard.remediationIssue.gap.conformity': 'Uygunluk kayıtları eksik',
  'dashboard.remediationIssue.independence.required': 'Bağımsız doğrulama zorunlu',
  'dashboard.remediationIssue.independence.recommended': 'Bağımsız inceleme önerilir',
  'dashboard.remediationIssue.independence.none': 'Bağımsızlık kapsamı bekleniyor',
  'dashboard.remediationArtifact.plan': 'Plan',
  'dashboard.remediationArtifact.standard': 'Standart',
  'dashboard.remediationArtifact.review': 'Gözden geçirme',
  'dashboard.remediationArtifact.analysis': 'Analiz',
  'dashboard.remediationArtifact.test': 'Test',
  'dashboard.remediationArtifact.coverage_stmt': 'Statement kapsamı',
  'dashboard.remediationArtifact.coverage_dec': 'Decision kapsamı',
  'dashboard.remediationArtifact.coverage_mcdc': 'MC/DC kapsamı',
  'dashboard.remediationArtifact.trace': 'İzlenebilirlik',
  'dashboard.remediationArtifact.cm_record': 'Konfigürasyon kaydı',
  'dashboard.remediationArtifact.qa_record': 'Kalite kaydı',
  'dashboard.remediationArtifact.problem_report': 'Problem raporu',
  'dashboard.remediationArtifact.conformity': 'Uygunluk kaydı',
  'dashboard.remediationArtifact.design': 'Tasarım artefaktı',
  'dashboard.independenceTitle': 'Bağımsızlık Denetimleri',
  'dashboard.independenceSubtitle': 'Bağımsız doğrulama gerektiren hedefler',
  'dashboard.independenceAllClear': 'Bağımsız doğrulama gerektiren tüm hedefler tamamlandı.',
  'dashboard.independenceUnavailable': 'Bağımsızlık özeti bulunamadı.',
  'dashboard.independenceOpenSummary': 'Açık bağımsız hedefler',
  'dashboard.independencePartial': 'Kısmi',
  'dashboard.independenceMissing': 'Eksik',
  'dashboard.independenceLinkLabel': 'Hedefe git',
  'dashboard.pendingReviews': 'Bekleyen İncelemeler',
  'dashboard.reviewError': 'İnceleme listesi alınamadı.',
  'dashboard.reviewErrorTitle': 'İncelemeler yüklenemedi',
  'dashboard.noPendingReviews': 'Bekleyen inceleme bulunmuyor',
  'dashboard.reviewId': 'İnceleme',
  'dashboard.reviewTarget': 'Hedef',
  'dashboard.reviewApprovers': 'Onaycılar',
  'dashboard.reviewUpdatedAt': 'Güncelleme',
  'dashboard.changeRequests': 'Jira Değişiklik Talepleri',
  'dashboard.changeRequestsError': 'Jira değişiklik talepleri alınamadı.',
  'dashboard.changeRequestsErrorTitle': 'Değişiklik talepleri yüklenemedi',
  'dashboard.changeRequestsEmpty': 'Bekleyen değişiklik talebi bulunmuyor',
  'dashboard.changeRequestsKey': 'Anahtar',
  'dashboard.changeRequestsSummary': 'Özet',
  'dashboard.changeRequestsStatus': 'Durum',
  'dashboard.changeRequestsAssignee': 'Atanan',
  'dashboard.changeRequestsUpdatedAt': 'Güncellendi',
  'dashboard.changeRequestsAttachments': 'Ekler',
  'dashboard.health': 'Sistem Sağlığı',
  'logs.title': 'Denetim Kayıtları',
  'logs.description': 'Tüm denetim olaylarını görüntüleyin ve dışa aktarın.',
  'logs.exportCsv': 'CSV Dışa Aktar',
  'logs.empty': 'Henüz kayıt bulunmuyor',
  'logs.error': 'Denetim kayıtları alınamadı.',
  'logs.errorTitle': 'Denetim kayıtları yüklenemedi',
  'logs.credentialsRequired': 'REST kimlik bilgileri gereklidir.',
  'logs.filter.tenant': 'Kiracı filtresi',
  'logs.filter.actor': 'Kullanıcı filtresi',
  'logs.table.timestamp': 'Zaman',
  'logs.table.actor': 'Kullanıcı',
  'logs.table.tenant': 'Kiracı',
  'logs.table.action': 'Eylem',
  'logs.table.target': 'Hedef',
  'notifications.success': 'Başarıyla kaydedildi',
  'settings.title': 'Yönetim Ayarları',
  'settings.description': 'Güvenlik, lisans ve güncelleme politikalarını yönetin.',
  'settings.tab.general': 'Genel',
  'settings.tab.security': 'Güvenlik',
  'settings.tab.license': 'Lisans',
  'settings.tab.updates': 'Güncellemeler',
  'settings.environment': 'Çalışma Ortamı',
  'settings.licenseSerial': 'Lisans Seri',
  'settings.licenseExpiry': 'Lisans Bitişi',
  'settings.features': 'Aktif Özellikler',
  'settings.updatePolicy': 'Güncelleme Politikası',
  'audit.banner': 'Denetim kayıtları kaydediliyor ve 90 gün saklanıyor.',
  'wizard.sign.cta': 'Ayarları Kaydet',
  'wizard.deploy.cta': 'Politikayı Güncelle',
  'status.up': 'Çevrimiçi',
  'status.down': 'Kapalı',
  'status.degraded': 'Kısmi Hizmet'
};

const dictionaries: Record<Locale, Record<string, string>> = {
  en: enTranslations,
  tr: trTranslations
};

export const availableLocales: readonly Locale[] = ['en', 'tr'] as const;

export const defaultLocale: Locale = 'en';

export function translate(locale: Locale, key: string): string {
  const dictionary = dictionaries[locale];
  return dictionary?.[key] ?? enTranslations[key] ?? key;
}
