name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Type check
        run: npm run typecheck
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
      - name: Validate OpenAPI
        run: npm run openapi:validate
      - name: Build Docker image
        run: docker build -t soipack/server .
      - name: Smoke test Docker image
        shell: bash
        run: |
          set -euo pipefail
          docker rm -f soipack-ci >/dev/null 2>&1 || true
          docker run -d --name soipack-ci \
            -p 3443:3443 \
            -v "${{ github.workspace }}/docker/testdata:/run/secrets:ro" \
            -e SOIPACK_AUTH_ISSUER=https://auth.example.test/ \
            -e SOIPACK_AUTH_AUDIENCE=soipack-api \
            -e SOIPACK_AUTH_JWKS_URI=https://auth.example.test/.well-known/jwks.json \
            -e SOIPACK_SIGNING_KEY_PATH=/run/secrets/signing-key.pem \
            -e SOIPACK_LICENSE_PUBLIC_KEY_PATH=/run/secrets/license.pub \
            -e SOIPACK_TLS_KEY_PATH=/run/secrets/ci-server.key \
            -e SOIPACK_TLS_CERT_PATH=/run/secrets/ci-server.crt \
            -e SOIPACK_STORAGE_DIR=/tmp/soipack \
            -e SOIPACK_HEALTHCHECK_TOKEN=ci-health-token \
            -e PORT=3443 \
            soipack/server

          success=false
          for attempt in {1..30}; do
            if curl --fail --silent --show-error \
              --cacert "${{ github.workspace }}/docker/testdata/ci-ca.crt" \
              -H "Authorization: Bearer ci-health-token" \
              https://localhost:3443/health; then
              success=true
              break
            fi
            sleep 2
          done

          if [[ "${success}" != "true" ]]; then
            docker logs soipack-ci || true
            docker rm -f soipack-ci >/dev/null 2>&1 || true
            exit 1
          fi

          if curl --fail --silent --show-error \
            -H "Authorization: Bearer ci-health-token" \
            https://localhost:3443/health; then
            echo "healthcheck unexpectedly succeeded without CA"
            docker rm -f soipack-ci >/dev/null 2>&1 || true
            exit 1
          fi

          docker rm -f soipack-ci >/dev/null 2>&1 || true
